# Generated by Django 3.1.1 on 2020-11-22 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_apartmentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentimage',
            name='imageFileApartment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='apartments.apartment'),
        ),
    ]
