# Generated by Django 3.1.1 on 2020-11-22 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_apartmentimage_imagefileapartment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartmentimage',
            old_name='imageFileApartment',
            new_name='apartment',
        ),
    ]
