# Generated by Django 2.2.2 on 2021-09-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('created_at', models.DateField()),
                ('modified_at', models.DateField()),
                ('is_canceled', models.BooleanField(default=False)),
                ('canceled_at', models.DateField()),
                ('total_price', models.IntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('stay_from', models.DateField()),
                ('stay_to', models.DateField()),
            ],
        ),
    ]
