# Generated by Django 3.1.1 on 2020-10-19 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extra_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraservice',
            name='extra_service_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='extra_services.extraservicecategory'),
        ),
        migrations.AlterField(
            model_name='extraservicecategory',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
